# Generated by Django 5.1.2 on 2024-10-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_created_at_alter_category_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cdd',
            field=models.FloatField(),
        ),
    ]
