# Generated by Django 5.1.2 on 2024-10-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_cdd'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='cdd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
